name: tasty_bytes
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  expandable_text: ^2.3.0
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.0
  fluttertoast: ^8.2.2
  google_nav_bar: ^5.0.6
  http: ^1.1.0
  path: ^1.8.3
  path_provider: ^2.1.1
  popover: ^0.2.8+2
  provider: ^6.0.5
  sqflite: ^2.3.0
  tuple: ^2.0.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/cuisine/
    - assets/icons/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
